import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from '@clerk/nextjs';
import ReactQueryProvider from "./provider/query";
import { FavoritesProvider } from "./hooks/useLike";

export const metadata: Metadata = {
  title: "Digital Shop",
  description: "Generated by create next app",
  icons: {
    icon:'/store.png'
  }
};

export default function RootLayout({children}: Readonly<{  children: React.ReactNode;}>) {
  return (
   <ClerkProvider appearance={{
    variables: {colorPrimary: "#4f46e5" },
  }}>
     <ReactQueryProvider>
      <html lang="en" suppressHydrationWarning>
      <body className="overflow-x-hidden">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <FavoritesProvider>
          <Header/>
          <div className="py-18"></div>
          <div className="px-20">{children}</div><br />
          <Toaster />
          <Footer/>
        </FavoritesProvider>
        </ThemeProvider>
      </body>
    </html>
     </ReactQueryProvider>
   </ClerkProvider>
  );
}
